Repository ldtteam/Structurize, pull requests merged in 2021-06, with the labels that each got.

#384 Fix items not being put into chests.
  src/api/java/com/ldtteam/structurize/api/util/ItemStackUtils.java
  src/main/java/com/ldtteam/structurize/client/gui/WindowScan.java
  src/main/java/com/ldtteam/structurize/placement/handlers/placement/PlacementHandlers.java
Labels: PR: Ready for Review

#385 Populates the `required_mods` list properly.
  src/main/java/com/ldtteam/structures/blueprints/v1/BlueprintUtil.java
Labels: PR: Ready for Review

#391 Fixes
  src/api/java/com/ldtteam/structurize/api/blocks/BlockType.java
  src/api/java/com/ldtteam/structurize/api/blocks/IBlockCollection.java
  src/main/java/com/ldtteam/structurize/Structurize.java
  src/main/java/com/ldtteam/structurize/blocks/ModBlocks.java
  src/main/java/com/ldtteam/structurize/client/gui/WindowReplaceBlock.java
  src/main/java/com/ldtteam/structurize/event/ClientLifecycleSubscriber.java
  src/main/java/com/ldtteam/structurize/event/LifecycleSubscriber.java
  src/main/java/com/ldtteam/structurize/items/ItemScanTool.java
  src/main/java/com/ldtteam/structurize/placement/handlers/placement/PlacementHandlers.java
  src/main/java/com/ldtteam/structurize/util/BlockUtils.java
  src/main/java/com/ldtteam/structurize/util/TickedWorldOperation.java
  src/main/resources/assets/structurize/lang/en_us.json
  src/main/resources/data/structurize/tags/blocks/null_placement.json
Labels: 1.16, PR: Ready for Review

#386 Fix anchors tileentities missing data
  src/api/java/com/ldtteam/structurize/api/util/BlockPosUtil.java
  src/main/java/com/ldtteam/structures/blueprints/v1/Blueprint.java
  src/main/java/com/ldtteam/structures/blueprints/v1/BlueprintUtil.java
  src/main/java/com/ldtteam/structurize/blocks/interfaces/IBlueprintDataProvider.java
  src/main/java/com/ldtteam/structurize/client/gui/WindowScan.java
  src/main/java/com/ldtteam/structurize/items/ItemScanTool.java
  src/main/java/com/ldtteam/structurize/tileentities/TileEntityMultiBlock.java
  src/main/resources/assets/structurize/lang/en_us.json
Labels: PR: Ready for Review

#351 Another attemp to fix scaling and lighting issue with icons
  src/main/java/com/ldtteam/blockout/BOScreen.java
  src/main/java/com/ldtteam/blockout/controls/ItemIcon.java
  src/main/java/com/ldtteam/blockout/views/ZoomDragView.java
  src/main/resources/assets/structurize/gui/windowscantool.xml
Labels: 1.16, Compatibility: Vanilla, PR: Ready for Review

#395 fix 394
  src/main/java/com/ldtteam/structurize/util/InventoryUtils.java
Labels: PR: Ready for Review

#397 Bump optifine compat
  src/main/java/com/ldtteam/structures/client/BlueprintRenderer.java
  src/main/java/com/ldtteam/structurize/optifine/OptifineCompat.java
Labels: PR: Ready for Review

#398 Circ alg
  src/api/java/com/ldtteam/structurize/api/util/BlockPosUtil.java
  src/main/java/com/ldtteam/structurize/config/AbstractConfiguration.java
  src/main/java/com/ldtteam/structurize/config/ServerConfiguration.java
  src/main/java/com/ldtteam/structurize/placement/AbstractBlueprintIterator.java
  src/main/java/com/ldtteam/structurize/placement/BlueprintIteratorDefault.java
  src/main/java/com/ldtteam/structurize/placement/BlueprintIteratorInwardCircle.java
  src/main/java/com/ldtteam/structurize/placement/BlueprintIteratorInwardCircleHeight.java
  src/main/java/com/ldtteam/structurize/placement/StructureIterators.java
  src/main/java/com/ldtteam/structurize/placement/StructurePlacer.java
  src/main/java/com/ldtteam/structurize/util/TickedWorldOperation.java
  src/main/resources/assets/structurize/lang/en_us.json
Labels: PR: Ready for Review

#404 fix item icon number rendering
  src/main/java/com/ldtteam/blockout/controls/ItemIcon.java
Labels: PR: Ready for Review
